  os: osx
  osx_image: xcode11
  language: android
  jdk: oraclejdk8

  env:
    global:
      - ANDROID_API_LEVEL=28
      - ANDROID_BUILD_TOOLS_VERSION=28.0.3

  android:
    components:
      - tools
      - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
      - platform-tools
      - android-${ANDROID_API_LEVEL}
      - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
      - extra

  script:
    - ./gradlew build
