name: Release

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run gradle build
      run: ./gradlew library:build
    - name: Run publish
      run: ./gradlew library:publish
      env:
        sonatypeUsernameEnv: ${{ secrets.SONATYPEUSERNAME }}
        sonatypePasswordEnv: ${{ secrets.SONATYPEPASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASS }}
